title: ACM@UIUC TIL
url: "https://til.acm.illinois.edu"
baseurl:
google_analytics_key:
show_full_navigation: true

# Dependencies
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
highlighter: rouge

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Things we learned.
author:
    name: ACM@UIUC
    email: officers@acm.illinois.edu
    twitter: ACM-UIUC
social:
  name: ACM@UIUC 
  links:
      - https://github.com/acm-uiuc

excerpt_separator: ""
permalink: pretty

gems:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - CONTRIBUTING.md

collections:
    til:
        title: Today I Learned
        permalink: /:path/
        output: true

defaults:
    -
        scope:
            path: ""
        values:
            layout: default
    -
        scope:
            path: ""
            type: "til"
        values:
            seo:
                type: Article
            _comments:
                category: Group navigation links with this field
                order: Used to sort links in the navigation
    -
        scope:
            path: ""
            type: "posts"
        values:
            _comments:
                type: Marks the impact of this release


types:
    - minor
    - major
